# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_csv <- function(file, n) {
    .Call('fastread_read_csv', PACKAGE = 'fastread', file, n)
}

read_all_lines_ifstream <- function(filename, n) {
    invisible(.Call('fastread_read_all_lines_ifstream', PACKAGE = 'fastread', filename, n))
}

read_all_lines_FILE <- function(filename) {
    invisible(.Call('fastread_read_all_lines_FILE', PACKAGE = 'fastread', filename))
}

