# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_csv <- function(file, n, classes) {
    .Call('fastread_read_csv', PACKAGE = 'fastread', file, n, classes)
}

allocate_vectors <- function(file, n, classes) {
    .Call('fastread_allocate_vectors', PACKAGE = 'fastread', file, n, classes)
}

count_lines <- function(file, n, classes) {
    .Call('fastread_count_lines', PACKAGE = 'fastread', file, n, classes)
}

