---
title: "Column types"
author: "Hadley Wickham"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Column types

Currently, readr automatically recognises the following types of columns:

* `col_logical()` [l], containing only `T`, `F`, `TRUE` or `FALSE`.
* `col_integer()` [i], integers.
* `col_double()` [d], doubles.
* `col_euro_double()` [e], "Euro" doubles that use `,` as decimal separator.
* `col_character()` [c], everything else.
* `col_date(format = "")` [D]: Y-m-d dates.
* `col_datetime(format = "", tz = "UTC")` [T]: ISO8601 date times

To recognise these columns, it reads the first 100 rows of your dataset. This is not guaranteed to be perfect, but it's fast and a reasonable heuristic. If you get a lot of parsing failures, you'll need to re-read the file, overriding the default choices as described below.

You can also manually specify other column types:

* `col_skip()` [_], don't import this column.

* `col_datetime(date)`, dates with given format.

* `col_datetime(format, tz)`, date times with given format. If the timezone
  is UTC, this is >20x faster than loading then parsing with `strptime()`.

* `col_numeric()` [n], a sloppy numeric parser that ignores everything apart from
   0-9, `-` and `.` (this is useful for parsing data formatted as currencies).

* `col_factor(levels, ordered)`, parse a fixed set of known values into a 
  factor

Use the `col_types` argument to override the default choices. There are two ways to use it:

* With a string: `"dc__d"`: read first column as double, second as character,
  skip the next two and read the last column as a double. (There's no way to
  use this form with types that take additional parameters.)

* With a (named) list of col objects:

    ```R
    read_csv("iris.csv", col_types = list(
      Sepal.Length = col_double(),
      Sepal.Width = col_double(),
      Petal.Length = col_double(),
      Petal.Width = col_double(),
      Species = col_factor(c("setosa", "versicolor", "virginica"))
    ))
    ```
    
    Any omitted columns will be parsed automatically, so the previous call is 
    equivalent to:
    
    ```R
    read_csv("iris.csv", col_types = list(
      Species = col_factor(c("setosa", "versicolor", "virginica"))
    )
    ```
