// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_csv
List read_csv(std::string file, int n, CharacterVector classes);
RcppExport SEXP fastread_read_csv(SEXP fileSEXP, SEXP nSEXP, SEXP classesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string file = Rcpp::as<std::string >(fileSEXP);
        int n = Rcpp::as<int >(nSEXP);
        CharacterVector classes = Rcpp::as<CharacterVector >(classesSEXP);
        List __result = read_csv(file, n, classes);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// allocate_vectors
List allocate_vectors(std::string file, int n, CharacterVector classes);
RcppExport SEXP fastread_allocate_vectors(SEXP fileSEXP, SEXP nSEXP, SEXP classesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string file = Rcpp::as<std::string >(fileSEXP);
        int n = Rcpp::as<int >(nSEXP);
        CharacterVector classes = Rcpp::as<CharacterVector >(classesSEXP);
        List __result = allocate_vectors(file, n, classes);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// count_lines
int count_lines(std::string file);
RcppExport SEXP fastread_count_lines(SEXP fileSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string file = Rcpp::as<std::string >(fileSEXP);
        int __result = count_lines(file);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parseDouble_strtod
double parseDouble_strtod(std::string file, int nd);
RcppExport SEXP fastread_parseDouble_strtod(SEXP fileSEXP, SEXP ndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string file = Rcpp::as<std::string >(fileSEXP);
        int nd = Rcpp::as<int >(ndSEXP);
        double __result = parseDouble_strtod(file, nd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parseDouble_double_conversion
double parseDouble_double_conversion(std::string file, int nd);
RcppExport SEXP fastread_parseDouble_double_conversion(SEXP fileSEXP, SEXP ndSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string file = Rcpp::as<std::string >(fileSEXP);
        int nd = Rcpp::as<int >(ndSEXP);
        double __result = parseDouble_double_conversion(file, nd);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
