// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fastread.h"
#include <Rcpp.h>

using namespace Rcpp;

// count_char_from_file
std::map<char,int> count_char_from_file(std::string x, std::string quote_ = "\"", bool backslash_escape = false, bool double_escape = false, bool include_alpha = false, bool include_num = false);
RcppExport SEXP fastread_count_char_from_file(SEXP xSEXP, SEXP quote_SEXP, SEXP backslash_escapeSEXP, SEXP double_escapeSEXP, SEXP include_alphaSEXP, SEXP include_numSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< std::string >::type quote_(quote_SEXP );
        Rcpp::traits::input_parameter< bool >::type backslash_escape(backslash_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type double_escape(double_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP );
        Rcpp::traits::input_parameter< bool >::type include_num(include_numSEXP );
        std::map<char,int> __result = count_char_from_file(x, quote_, backslash_escape, double_escape, include_alpha, include_num);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// count_char_from_string
std::map<char,int> count_char_from_string(std::string x, std::string quote_ = "\"", bool backslash_escape = false, bool double_escape = false, bool include_alpha = false, bool include_num = false);
RcppExport SEXP fastread_count_char_from_string(SEXP xSEXP, SEXP quote_SEXP, SEXP backslash_escapeSEXP, SEXP double_escapeSEXP, SEXP include_alphaSEXP, SEXP include_numSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< std::string >::type quote_(quote_SEXP );
        Rcpp::traits::input_parameter< bool >::type backslash_escape(backslash_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type double_escape(double_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type include_alpha(include_alphaSEXP );
        Rcpp::traits::input_parameter< bool >::type include_num(include_numSEXP );
        std::map<char,int> __result = count_char_from_string(x, quote_, backslash_escape, double_escape, include_alpha, include_num);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// empty_cols
std::vector<bool> empty_cols(std::string x);
RcppExport SEXP fastread_empty_cols(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        std::vector<bool> __result = empty_cols(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// read_lines
CharacterVector read_lines(SEXP input, int n = 0);
RcppExport SEXP fastread_read_lines(SEXP inputSEXP, SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type input(inputSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        CharacterVector __result = read_lines(input, n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// count_lines
int count_lines(SEXP input, bool header = false);
RcppExport SEXP fastread_count_lines(SEXP inputSEXP, SEXP headerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type input(inputSEXP );
        Rcpp::traits::input_parameter< bool >::type header(headerSEXP );
        int __result = count_lines(input, header);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parse_text
SEXP parse_text(CharacterVector x, std::string what);
RcppExport SEXP fastread_parse_text(SEXP xSEXP, SEXP whatSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< std::string >::type what(whatSEXP );
        SEXP __result = parse_text(x, what);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// flip
List flip(ListOf<CharacterVector> x);
RcppExport SEXP fastread_flip(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< ListOf<CharacterVector> >::type x(xSEXP );
        List __result = flip(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// is_double
bool is_double(CharacterVector x);
RcppExport SEXP fastread_is_double(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP );
        bool __result = is_double(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// is_int
bool is_int(CharacterVector x);
RcppExport SEXP fastread_is_int(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP );
        bool __result = is_int(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parse_delimited_fields
std::vector<std::string> parse_delimited_fields(std::string x, std::string delim_ = ",", std::string quote_ = "\"", bool collapse = false, bool backslash_escape = false, bool double_escape = false, bool strict = false);
RcppExport SEXP fastread_parse_delimited_fields(SEXP xSEXP, SEXP delim_SEXP, SEXP quote_SEXP, SEXP collapseSEXP, SEXP backslash_escapeSEXP, SEXP double_escapeSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< std::string >::type delim_(delim_SEXP );
        Rcpp::traits::input_parameter< std::string >::type quote_(quote_SEXP );
        Rcpp::traits::input_parameter< bool >::type collapse(collapseSEXP );
        Rcpp::traits::input_parameter< bool >::type backslash_escape(backslash_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type double_escape(double_escapeSEXP );
        Rcpp::traits::input_parameter< bool >::type strict(strictSEXP );
        std::vector<std::string> __result = parse_delimited_fields(x, delim_, quote_, collapse, backslash_escape, double_escape, strict);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parse_fixed_fields
CharacterVector parse_fixed_fields(std::string x, IntegerVector start, IntegerVector end);
RcppExport SEXP fastread_parse_fixed_fields(SEXP xSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type end(endSEXP );
        CharacterVector __result = parse_fixed_fields(x, start, end);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parse_lines_from_string
std::vector<std::string> parse_lines_from_string(std::string x, int skip = 0, int n = 0, std::string delim_ = "\n", std::string comment_ = "");
RcppExport SEXP fastread_parse_lines_from_string(SEXP xSEXP, SEXP skipSEXP, SEXP nSEXP, SEXP delim_SEXP, SEXP comment_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type skip(skipSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< std::string >::type delim_(delim_SEXP );
        Rcpp::traits::input_parameter< std::string >::type comment_(comment_SEXP );
        std::vector<std::string> __result = parse_lines_from_string(x, skip, n, delim_, comment_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parse_lines_from_file
std::vector<std::string> parse_lines_from_file(std::string x, int skip = 0, int n = 0, std::string delim_ = "\n", std::string comment_ = "");
RcppExport SEXP fastread_parse_lines_from_file(SEXP xSEXP, SEXP skipSEXP, SEXP nSEXP, SEXP delim_SEXP, SEXP comment_SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type skip(skipSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< std::string >::type delim_(delim_SEXP );
        Rcpp::traits::input_parameter< std::string >::type comment_(comment_SEXP );
        std::vector<std::string> __result = parse_lines_from_file(x, skip, n, delim_, comment_);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// read_csv
List read_csv(std::string path, CharacterVector classes, CharacterVector col_names, int n = 0, int skip = 0);
RcppExport SEXP fastread_read_csv(SEXP pathSEXP, SEXP classesSEXP, SEXP col_namesSEXP, SEXP nSEXP, SEXP skipSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type path(pathSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type classes(classesSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type col_names(col_namesSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< int >::type skip(skipSEXP );
        List __result = read_csv(path, classes, col_names, n, skip);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// read_file
String read_file(const std::string& path);
RcppExport SEXP fastread_read_file(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP );
        String __result = read_file(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
