# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collectorGuess <- function(input, locale_) {
    .Call('readr_collectorGuess', PACKAGE = 'readr', input, locale_)
}

read_connection_ <- function(con, chunk_size = 64 * 1024L) {
    .Call('readr_read_connection_', PACKAGE = 'readr', con, chunk_size)
}

utctime <- function(year, month, day, hour, min, sec, psec) {
    .Call('readr_utctime', PACKAGE = 'readr', year, month, day, hour, min, sec, psec)
}

dim_tokens_ <- function(sourceSpec, tokenizerSpec) {
    .Call('readr_dim_tokens_', PACKAGE = 'readr', sourceSpec, tokenizerSpec)
}

count_fields_ <- function(sourceSpec, tokenizerSpec, n_max) {
    .Call('readr_count_fields_', PACKAGE = 'readr', sourceSpec, tokenizerSpec, n_max)
}

guess_header_ <- function(sourceSpec, tokenizerSpec, locale_) {
    .Call('readr_guess_header_', PACKAGE = 'readr', sourceSpec, tokenizerSpec, locale_)
}

tokenize_ <- function(sourceSpec, tokenizerSpec, n_max) {
    .Call('readr_tokenize_', PACKAGE = 'readr', sourceSpec, tokenizerSpec, n_max)
}

parse_vector_ <- function(x, collectorSpec, locale_, na) {
    .Call('readr_parse_vector_', PACKAGE = 'readr', x, collectorSpec, locale_, na)
}

read_file_ <- function(sourceSpec, locale_) {
    .Call('readr_read_file_', PACKAGE = 'readr', sourceSpec, locale_)
}

read_lines_ <- function(sourceSpec, locale_, n_max = -1L, progress = TRUE) {
    .Call('readr_read_lines_', PACKAGE = 'readr', sourceSpec, locale_, n_max, progress)
}

read_lines_raw_ <- function(sourceSpec, n_max = -1L, progress = FALSE) {
    .Call('readr_read_lines_raw_', PACKAGE = 'readr', sourceSpec, n_max, progress)
}

read_tokens <- function(sourceSpec, tokenizerSpec, colSpecs, colNames, locale_, n_max = -1L, progress = TRUE) {
    .Call('readr_read_tokens', PACKAGE = 'readr', sourceSpec, tokenizerSpec, colSpecs, colNames, locale_, n_max, progress)
}

guess_types_ <- function(sourceSpec, tokenizerSpec, locale_, n = 100L) {
    .Call('readr_guess_types_', PACKAGE = 'readr', sourceSpec, tokenizerSpec, locale_, n)
}

whitespaceColumns <- function(sourceSpec, n = 100L) {
    .Call('readr_whitespaceColumns', PACKAGE = 'readr', sourceSpec, n)
}

type_convert_col <- function(x, spec, locale_, col, na, trim_ws) {
    .Call('readr_type_convert_col', PACKAGE = 'readr', x, spec, locale_, col, na, trim_ws)
}

stream_delim <- function(df, path, delim, na, col_names = TRUE, append = FALSE) {
    .Call('readr_stream_delim', PACKAGE = 'readr', df, path, delim, na, col_names, append)
}

